AnnouncementWebsite/Components/NavigationViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AnnouncementWebsite.Repositories;
using AnnouncementWebsite.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AnnouncementWebsite.Components
{
    public class NavigationViewComponent : ViewComponent
    {
        private readonly ICategoryRepository _categoryRepository;

        public NavigationViewComponent(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            AnnouncementListViewModel announcementListViewModel = new AnnouncementListViewModel();
            announcementListViewModel.Categories = _categoryRepository.AllCategories;
            return await Task.FromResult((IViewComponentResult) View("Navigation", announcementListViewModel));
        }
    }
}

AnnouncementWebsite/Controllers/AnnouncementController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AnnouncementWebsite.Models;
using AnnouncementWebsite.Repositories;
using AnnouncementWebsite.Services;
using AnnouncementWebsite.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AnnouncementWebsite.Controllers
{
    public class AnnouncementController : Controller
    {
        private readonly UserManager<AplicationUser> _userManager;
        private readonly IAnnouncementRepository _announcementRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly AnnouncementControllerService _announcementControllerService;
        private readonly AnnouncementContext _announcementContext;

        public AnnouncementController(IAnnouncementRepository announcementRepository, ICategoryRepository categoryRepository,
            UserManager<AplicationUser> userManager,AnnouncementControllerService announcementControllerService,
            AnnouncementContext announcementContext)
        {
            _announcementContext = announcementContext;
            _announcementControllerService = announcementControllerService;
            _userManager = userManager;
            _announcementRepository = announcementRepository;
            _categoryRepository = categoryRepository;
        }

        public IActionResult AnnouncementList(string category,string SearchString)
        {
            IEnumerable<Announcement> announcements = new List<Announcement>();
            Category currentCategory = new Category();
            string categoryName = null;
            if (category != null & category !="All")
            {
                categoryName = category;
                if(SearchString !=null)
                {
                    announcements = _announcementRepository.SimilarAnnouncements(SearchString, categoryName).OrderBy(a=>a.AnnouncementId);
                }
                else
                {
                    announcements = _announcementRepository.AllAnnouncements
                        .Where(a => a.Category.CategoryName == category)
                        .OrderBy(a => a.AnnouncementId);
                }
                currentCategory = _categoryRepository.AllCategories.FirstOrDefault(c => c.CategoryName == category);
                
                return View(new AnnouncementListViewModel
                {
                    Announcements = announcements,
                    CurrentCategory = currentCategory
                });
            }

            else
            {
                if (SearchString != null)
                {
                    announcements = _announcementRepository.SimilarAnnouncements(SearchString, categoryName).OrderBy(a => a.AnnouncementId);

                }
                currentCategory = new Category() { CategoryName = "All" };
                return View(new AnnouncementListViewModel
                {
                    Announcements = announcements,
                    CurrentCategory = currentCategory
                });

            }
        }

        public async Task<IActionResult> AnnouncementDetails(int id)
        {
            var announcement = await _announcementRepository.GetAnnouncementById(id);
            if (announcement == null)
                return NotFound();
            var similarAnnouncements =  _announcementRepository.SimilarAnnouncements(announcement).Take(3);
            return View(new AnnouncementListViewModel
            {
                Announcements = similarAnnouncements,
                Announcement = announcement
            });
        }
        public async Task<IActionResult> EditAnnouncement(int id)
        {
            if (id != null)
            {
                var announcement = await _announcementRepository.GetAnnouncementById(id);
                if (announcement == null)
                    return NotFound();
                var editAnnouncement = new EditAnnouncementViewModel()
                {
                    AnnouncementId = announcement.AnnouncementId,
                    Title = announcement.Title,
                    Description = announcement.Description
                };
                return View(editAnnouncement);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> EditAnnouncement(EditAnnouncementViewModel editAnnouncement)
        {
            var announcement = await _announcementRepository.GetAnnouncementById(editAnnouncement.AnnouncementId);

            announcement.Title = editAnnouncement.Title;
            announcement.Description = editAnnouncement.Description;
            announcement.DateAdded = DateTime.Now.ToString("MM/dd/yyyy hh:mm tt");

            _announcementContext.Announcements.Update(announcement);
            await _announcementContext.SaveChangesAsync();
            return RedirectToAction("AnnouncementDetails" ,new {id = announcement.AnnouncementId});
        }


        [HttpPost]
        public async Task<IActionResult> DeleteAnnouncement(int id)
        {
            var announcement = await _announcementRepository.GetAnnouncementById(id);
            if (announcement != null)
            {
                await _announcementControllerService.DeleteImages(announcement);
                _announcementContext.Announcements.Remove(announcement);
                await _announcementContext.SaveChangesAsync();
            }

            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public ViewResult AddAnnouncement()
        {
            AnnouncementListViewModel announcementListViewModel = new AnnouncementListViewModel();
            announcementListViewModel.Categories = _categoryRepository.AllCategories;
            return View(announcementListViewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddAnnouncement(Announcement announcement, IFormFile file)
        {
            var userId = _userManager.GetUserId(User);
            var imageName = await _announcementControllerService.UploadImages(file, userId);

            if (ModelState.IsValid & imageName != null)
            {
                announcement.DateAdded = DateTime.Now.ToString("dd/MM/yyyy HH:mm");
                announcement.AplicationUserId = userId;

                _announcementContext.Announcements.Add(announcement);
                _announcementContext.SaveChanges();

                Image image = new Image();
                image.Name = imageName;
                AnnouncementImage announcementImage = new AnnouncementImage();
                _announcementContext.Images.Add(image);
                _announcementContext.SaveChanges();

                announcementImage.AnnouncementId = announcement.AnnouncementId;
                announcementImage.Image = image;
                _announcementContext.AnnouncementImages.Add(announcementImage);
                _announcementContext.SaveChanges();

                return RedirectToActionPermanent("Index", "Home");
            }

            ViewBag.Message = "Please upload the photo";
            return View(new AnnouncementListViewModel
            {
                Announcement = announcement,
                Categories = _categoryRepository.AllCategories
            });

        }

        public IActionResult MyAnnouncementList()
        {
            var userId = _userManager.GetUserId(User);
            var myAnnouncement =  _announcementRepository.AllAnnouncements.Where(a => a.AplicationUserId == userId);

            return View(new AnnouncementListViewModel
            {
                Announcements = myAnnouncement
            });
        }
       
    }
}

AnnouncementWebsite/Views/Shared/_AnnouncementCard.cshtml
@model Announcement
@foreach (var announcement in @Model.AnnouncementImages)
{
    <div class="col-md-4">
        <a asp-controller="Announcement" asp-action="AnnouncementDetails" asp-route-id="@announcement.AnnouncementId">
        <div class="card mb-4 shadow-sm">
            <img class="bd-placeholder-img card-img-top" width="100%" height="250" src="@String.Concat("https://myannouncement.s3.us-east-2.amazonaws.com/",
                                                                                            announcement.Image.Name)" />
            <div class="card-body">
                <p class="card-title">@Model.Title</p>
                <div class="d-flex justify-content-between align-items-center">
                    <p class="card-text">@Model.Description</p>
                    <div class="btn-group">
                    </div>
                    <small class="text-muted">@Model.DateAdded</small>
                </div>
            </div>
        </div>
    </a>
</div>
}

AnnouncementWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <title>Announcement</title>

    <!-- Bootstrap core CSS -->
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/content/site.css" rel="stylesheet">
</head>
<body>
    <header>
        @await Component.InvokeAsync("Navigation")
    </header>
<div id ="wrap">
    @RenderBody()
       
</div>
<!-- Footer -->
<footer>
    <div class="footer-dark">
        <div class="container">
            <div class="row">
                <div class="col item social">
                    <a href="https://www.facebook.com/dima.lushchevskyi"><i class="fa fa-facebook"></i></a>
                    <a href="https://github.com/Delirios"><i class="fa fa-github"></i></a>
                    <a href="https://www.instagram.com/__dimas1ck__"><i class="fa fa-instagram"></i></a>
                    <a href="https://www.linkedin.com/in/%D0%B4%D0%BC%D0%B8%D1%82%D1%80%D0%BE-%D0%BB%D1%83%D1%89%D0%B5%D0%B2%D1%81%D1%8C%D0%BA%D0%B8%D0%B9-86a30b1b2/"><i class="fa fa-linkedin"></i></a>
                </div>
            </div>
            <p class="copyright">Announcement website</p>
        </div>
    </div>
</footer>
<!-- Footer -->
    @RenderSection("Scripts", required: false)

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="~/lib/jquery/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src ="~/content/js.js"></script>
</body>
</html>

AnnouncementWebsite/Views/Shared/_Search.cshtml
@model AnnouncementListViewModel

<section class="jumbotron text-center">
    <h1> Search announcement</h1>
    @if (ViewData["CurrentCategory"] == null)
    {
        <form asp-controller="Announcement" asp-action="AnnouncementList">
            <div class="input-group mb-3 input-group-lg">
                <input type="text" name="SearchString" class="form-control" placeholder="Search">
                <div class="input-group-append">
                    <button asp- class="btn btn-success" type="submit">Go</button>
                </div>
            </div>
        </form>
    }
    else
    {
    <form asp-controller="Announcement" asp-action="AnnouncementList" asp-route-category="@ViewData["CurrentCategory"]">
        <div class="input-group mb-3 input-group-lg">
            <input type="text" name="SearchString" class="form-control" placeholder="Search">
            <div class="input-group-append">
                <button asp- class="btn btn-success" type="submit">Go</button>
            </div>
        </div>
    </form>
    }
</section>